# -*- coding: utf-8 -*-
"""Reconhecimento de CAT vs Dogs

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rKPSjyK5cVhuzb0W0CqF8kijxuE_fRlv

#Codigo Bruto
"""

import os
import zipfile
import urllib.request
import random
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.applications import VGG16
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout
from PIL import Image # Import PIL for image validation

# URL do dataset e configuração de pastas
DATA_URL = (
    "https://download.microsoft.com/download/3/E/1/"
    "3E1C3F21-ECDB-4869-8368-6DEBA77B919F/kagglecatsanddogs_5340.zip"
)
EXTRACT_PATH = "cats_and_dogs"

# Função para baixar e extrair os dados
def download_and_extract_data(url, extract_path):
    zip_path = "dataset.zip"
    if not os.path.exists(extract_path):
        print("Baixando dataset...")
        urllib.request.urlretrieve(url, zip_path)
        print("Extraindo dataset...")
        with zipfile.ZipFile(zip_path, 'r') as zip_ref:
            zip_ref.extractall(extract_path)
        os.remove(zip_path)
        print("Dataset preparado!")
    else:
        print("Dataset já está preparado.")

download_and_extract_data(DATA_URL, EXTRACT_PATH)

# Define o diretório base para as imagens
base_dir = os.path.join(EXTRACT_PATH, "PetImages")

# Função para limpar diretórios do dataset (remove arquivos problemáticos conhecidos e .DS_Store)
def clean_dataset_directories(base_dir):
    print("Iniciando limpeza do dataset (arquivos conhecidos e .DS_Store)...")
    # Arquivos corrompidos conhecidos neste dataset
    corrupted_files = [
        os.path.join(base_dir, 'Cat', '666.jpg'),
        os.path.join(base_dir, 'Dog', '11397.jpg')
    ]
    for root, _, files in os.walk(base_dir):
        for file in files:
            file_path = os.path.join(root, file)
            if file == '.DS_Store': # Remove macOS specific hidden files
                try:
                    os.remove(file_path)
                    print(f"Removido arquivo .DS_Store: {file_path}")
                except OSError as e:
                    print(f"Erro ao remover .DS_Store: {file_path} - {e}")
            elif file_path in corrupted_files: # Remove specific known corrupted images
                try:
                    os.remove(file_path)
                    print(f"Removido arquivo corrompido conhecido: {file_path}")
                except OSError as e:
                    print(f"Erro ao remover arquivo corrompido: {file_path} - {e}")
    print("Limpeza inicial do dataset concluída.")

def remove_corrupt_images(directory):
    print(f"Verificando e removendo imagens corrompidas em: {directory}...")
    removed_count = 0
    for root, _, files in os.walk(directory):
        for filename in files:
            if filename.lower().endswith(('.png', '.jpg', '.jpeg', '.gif', '.bmp')):
                filepath = os.path.join(root, filename)
                try:
                    img = Image.open(filepath)
                    img.verify() # Verify image integrity
                    img.close()
                except Exception as e:
                    print(f"AVISO: Imagem corrompida ou ilegível encontrada e removida: {filepath} - {e}")
                    try:
                        os.remove(filepath)
                        removed_count += 1
                    except OSError as e_remove:
                        print(f"ERRO: Não foi possível remover o arquivo corrompido: {filepath} - {e_remove}")
    print(f"Verificação de imagens concluída. Total de imagens corrompidas removidas: {removed_count}")

# Chama a função de limpeza antes de configurar os geradores de dados
clean_dataset_directories(base_dir)
remove_corrupt_images(base_dir)

# Configuração do gerador de dados
datagen = ImageDataGenerator(
    rescale=1.0 / 255,
    validation_split=0.2  # 20% dos dados para validação
)

# Criar geradores de treino e validação
train_generator = datagen.flow_from_directory(
    base_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    subset='training'
)

validation_generator = datagen.flow_from_directory(
    base_dir,
    target_size=(224, 224),
    batch_size=32,
    class_mode='binary',
    subset='validation'
)

# Carregar o modelo VGG16 pré-treinado
base_model = VGG16(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
base_model.trainable = False  # Congelar as camadas da base do modelo

# Construir o modelo com transferência de aprendizado
model = Sequential([
    base_model,
    Flatten(),
    Dense(256, activation='relu'),
    Dropout(0.5),
    Dense(1, activation='sigmoid')  # Camada de saída para classificação binária
])

# Compilar o modelo
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

# Treinamento do modelo
history = model.fit(
    train_generator,
    validation_data=validation_generator,
    epochs=10,
    verbose=1
)

# Função para plotar os resultados
def plot_training_history(history):
    plt.figure(figsize=(12, 4))
    # Loss
    plt.subplot(1, 2, 1)
    plt.plot(history.history['loss'], label='Loss - Treino')
    plt.plot(history.history['val_loss'], label='Loss - Validação')
    plt.legend()
    plt.title('Loss durante o Treinamento')
    # Accuracy
    plt.subplot(1, 2, 2)
    plt.plot(history.history['accuracy'], label='Accuracy - Treino')
    plt.plot(history.history['val_accuracy'], label='Accuracy - Validação')
    plt.legend()
    plt.title('Accuracy durante o Treinamento')
    plt.show()

# Plotar histórico do treinamento
plot_training_history(history)

# Avaliação final no conjunto de validação
loss, accuracy = model.evaluate(validation_generator, verbose=0)
print(f"Loss final: {loss:.4f}")
print(f"Accuracy final: {accuracy:.4f}")

import os
import numpy as np
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.vgg16 import preprocess_input
from google.colab import files

def predict_image(image_path):
    try:
        img = image.load_img(image_path, target_size=(224, 224))
        x = image.img_to_array(img)
        x = np.expand_dims(x, axis=0)
        x = preprocess_input(x)
        preds = model.predict(x)
        if preds[0][0] >= 0.5:
            return "Cachorro"
        else:
            return "Gato"
    except Exception as e:
        return f"Erro na predição: {e}"

# Fazer upload do arquivo
uploaded = files.upload()

# Verificar se o arquivo foi carregado
if uploaded:
    uploaded_file_path = list(uploaded.keys())[0]
    prediction = predict_image(uploaded_file_path)
    print(f"Predição: {prediction}")
else:
    print("Nenhum arquivo foi carregado.")